BEGIN;
CREATE TABLE products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name TEXT NOT NULL,
    uni_price NUMERIC NOT NULL
    description TEXT,
    inStock INTEGER  DEFAULT 0,
    provider TEXT NOT NULL

);
COMMIT;
