BEGIN;
CREATE TABLE orders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    client TEXT NOT NULL,
    client_email text,
    order_total numeric NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
COMMIT;