BEGIN;
CREATE TABLE orders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- user_id INTEGER REFERENCES user(id) NOT NULL
    client TEXT NOT NULL,
    client_email text,
    order_total numeric NOT NULL
    -- CREATED AT
);
COMMIT;